using System;
using NUnit.Framework;
using DotnetMvcBoilerplate.Controllers;
using System.Web.Mvc;
using AutoMoq;
using DotnetMvcBoilerplate.ViewModels.Install;
using DotnetMvcBoilerplate.Tests.Unit.Utils;
using DotnetMvcBoilerplate.Models;
using DotnetMvcBoilerplate.Core.Service;
using Moq;

namespace DotnetMvcBoilerplate.Tests.Unit.Controllers
{
    public class InstallControllerTests
    {
        private AutoMoqer _autoMoqer;

        [SetUp]
        public void Setup()
        {
            _autoMoqer = new AutoMoqer();
        }

        /// <summary>
        /// Tests that a GET request to Index will return the install form.
        /// </summary>
        [Test]
        public void Index_HttpGetWhereInstallHasntHappened_ReturnsView()
        {
            _autoMoqer.GetMock<IUserService>().Setup(x => x.AtLeastOneExists()).Returns(false);
            Assert.That(_autoMoqer.Resolve<InstallController>().Index(), Is.InstanceOf<ViewResult>());
        }

        /// <summary>
        /// Tests that a GET request to Index when the install has already happened redirects
        /// the client to the root page of the website.
        /// </summary>
        [Test]
        public void Index_HttpGetWhereInstallHasAlreadyHappened_RedirectsToRoot()
        {
            _autoMoqer.GetMock<IUserService>().Setup(x => x.AtLeastOneExists()).Returns(true);
            Assert.That((_autoMoqer.Resolve<InstallController>().Index() as RedirectResult).Url, Is.EqualTo("/"));
        }

        /// <summary>
        /// Tests that a POST request with an invalid Model will return
        /// the install form with the model passed to Index.
        /// </summary>
        [Test]
        public void Index_HttpPostWithInvalidModel_ReturnsViewWithModel()
        {
            var expectedModel = _autoMoqer.Create<InstallViewModel>();
            var installController = _autoMoqer.Resolve<InstallController>();
            ControllerTestsUtils.SetModelStateAsInvalid(installController);

            Assert.That((installController.Index(expectedModel) as ViewResult).Model, Is.EqualTo(expectedModel));
        }

        /// <summary>
        /// Tests that a POST request with a valid Model will redirect
        /// the user to the home page.
        /// </summary>
        [Test]
        public void Index_HttpPostWithValidModel_RedirectsToRoot()
        {
            Assert.That((_autoMoqer.Resolve<InstallController>().Index(_autoMoqer.GetMock<InstallViewModel>().Object) as RedirectResult).Url, Is.EqualTo("/"));
        }

        /// <summary>
        /// Tests that a POST request with a valid Model will call Create on the UserService
        /// with a instance of User that is generated by the model.
        /// </summary>
        [Test]
        public void Index_HttpPostWithValidModel_CallsCreateOnUserServiceWithUserFromModel()
        {
            var expectedUser = new User();
            var mockInstallViewModel = _autoMoqer.GetMock<InstallViewModel>();
            mockInstallViewModel.Setup(x => x.ToUser()).Returns(expectedUser);

            _autoMoqer.Resolve<InstallController>().Index(mockInstallViewModel.Object);

            _autoMoqer.GetMock<IUserService>().Verify(x => x.Create(expectedUser), Times.Once());
        }
    }
}
